<?php  //[STAMP] 53bba2d8119e0c40b0f781c2ea1b1a00
namespace FrameworkTests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
